### PR TITLE
[CS-032] Finishes Clan implementation

### LINKED ISSUE #34: Bug: package com.sun.[...] does not exist
Error:(3,31) java: package com.sun.istack.internal does not exist
  in de\codingair\clansystem\spigot\base\managers\ClanManager.java

### PR DESCRIPTION
**Pull request by erikzimmermann**
Closes #34

### CODE REVIEW

File: src/main/java/de/codingair/clansystem/utils/clan/Clan.java [hunk 1]
```diff
@@ -128,15 +326,14 @@ public UUID getMemberByRank(Rank rank) {
         } else return null;
     }
 
-    public boolean hasPermission(UUID uuid, Permission permission) {
-        Rank r = getRank(uuid);
-        return r != null && r.hasPermission(permission);
-    }
-
     public Rank getRank(UUID uuid) {
```
Comment (dorsax) [inline src/main/java/de/codingair/clansystem/utils/clan/Clan.java]: I would like to see this to have no conflict
```suggestion
    public Rank getMemberRank(UUID uuid) {
```

File: src/main/java/de/codingair/clansystem/utils/clan/Clan.java [hunk 2]
```diff
@@ -128,15 +326,14 @@ public UUID getMemberByRank(Rank rank) {
...
         return members.get(uuid);
     }
 
+    public Rank getRank(int id) {
```
Comment (dorsax) [inline src/main/java/de/codingair/clansystem/utils/clan/Clan.java]: To avoid conflicts with the other `getRank()`, I would like this method name
```suggestion
    public Rank getClanRank(int id) {
```

**Review by dorsax — APPROVED** [review]
